### ISSUE TITLE
Segfault in branch_get_upstream

### ISSUE THREAD

**Issue by stewid** [libgit2/libgit2#3140]
@krlmlr reported a segfault from the R bindings git2r in branch_get_upstream, see https://github.com/ropensci/git2r/issues/134

I can reproduce the segfault with the code below, after adding the following to the `.gitconfig`

```
[remote "origin"]
        push = :
```

I have tested on linux with libgit2 built from commit 0aa603363e39e51e8313a2952710f565141080cb

```
#include <git2.h>

int main(int argc, char **argv)
{
    if (argc > 1) {
        git_reference *reference = NULL;
        git_reference *upstream = NULL;
        git_repository *repository = NULL;
        const char *repo_path = argv[1];

        git_libgit2_init();

        if (git_repository_open(&repository, repo_path))
            exit(1);

        if (git_branch_lookup(&reference, repository, "master", GIT_BRANCH_LOCAL))
            exit(1);

        if (git_branch_upstream(&upstream, reference))
            exit(1);

        git_repository_free(repository);
        git_reference_free(reference);
        git_reference_free(upstream);

        git_libgit2_shutdown();
    }

    return 0;
}
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff777baea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) backtrace
#0  0x00007ffff777baea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff777b82e in strdup () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7b657e1 in git__strdup (str=0x0)
    at /home/stefan/temp/libgit2/src/util.h:170
#3  0x00007ffff7b66414 in git_refspec__dwim_one (out=0x61ef48, spec=0x61f550,
    refs=0x61eef8) at /home/stefan/temp/libgit2/src/refspec.c:311
#4  0x00007ffff7b72dc8 in dwim_refspecs (out=0x61ef48, refspecs=0x61ef20,
    refs=0x61eef8) at /home/stefan/temp/libgit2/src/remote.c:816
#5  0x00007ffff7b7226a in git_remote_lookup (out=0x7fffffffe438,
    repo=0x61d0f0, name=0x61d230 "origin")
    at /home/stefan/temp/libgit2/src/remote.c:502
#6  0x00007ffff7b2a759 in git_branch_upstream_name (out=0x7fffffffe4f0,
    repo=0x61d0f0, refname=0x61cebc "refs/heads/master")
    at /home/stefan/temp/libgit2/src/branch.c:382
#7  0x00007ffff7b2abc5 in git_branch_upstream (tracking_out=0x7fffffffe550,
    branch=0x61ce80) at /home/stefan/temp/libgit2/src/branch.c:508
#8  0x0000000000400976 in main ()
```

**Comment by carlosmn** [comment]
There's a fix for the crash in #3149 though if you only have that push refspec for your remote, with no fetch refspecs, you're not going to be able to find any upstream branches.

**Comment by krlmlr** [comment]
Thanks. This was our attempt at generating a minimal example -- the full config where the issue originally occurred contains more than that.

**Comment by stewid** [comment]
@carlosmn Thanks
