### ISSUE TITLE
0.23.0 Crashes during test of object cache

### ISSUE THREAD

**Issue by russell** [libgit2/libgit2#3330]
Hey,

I by chance saw this crash happen on one machine and have been able to reproduce by running the libgit2_clar test suite over and over again.  It took about 31 times to reproduce it.

```
#0  0x0000000000439c3e in pack_entry_find_offset (offset_out=0x7fffdbffec10, found_oid=0x7fffdbffebf0, p=0x7fffe4009080, 
    short_oid=0x7fffdbffeee0, len=40) at /home/russell/projects/debian/libgit2/src/pack.c:1289
#1  0x0000000000439ea4 in git_pack_entry_find (e=0x7fffdbffed00, p=0x7fffe4009080, short_oid=0x7fffdbffeee0, len=40)
    at /home/russell/projects/debian/libgit2/src/pack.c:1374
#2  0x0000000000445b0c in pack_entry_find_inner (e=0x7fffdbffed00, backend=0x7fffe4000cf0, oid=0x7fffdbffeee0, last_found=0x0)
    at /home/russell/projects/debian/libgit2/src/odb_pack.c:247
#3  0x0000000000445bb9 in pack_entry_find (e=0x7fffdbffed00, backend=0x7fffe4000cf0, oid=0x7fffdbffeee0)
    at /home/russell/projects/debian/libgit2/src/odb_pack.c:264
#4  0x0000000000445fc2 in pack_backend__read_internal (buffer_p=0x7fffdbffedb0, len_p=0x7fffdbffedb8, type_p=0x7fffdbffedc0, 
    backend=0x7fffe4000cf0, oid=0x7fffdbffeee0) at /home/russell/projects/debian/libgit2/src/odb_pack.c:389
#5  0x0000000000446051 in pack_backend__read (buffer_p=0x7fffdbffedb0, len_p=0x7fffdbffedb8, type_p=0x7fffdbffedc0, 
    backend=0x7fffe4000cf0, oid=0x7fffdbffeee0) at /home/russell/projects/debian/libgit2/src/odb_pack.c:406
#6  0x00000000004836b1 in git_odb_read (out=0x7fffdbffee58, db=0x7fffe4000aa0, id=0x7fffdbffeee0)
    at /home/russell/projects/debian/libgit2/src/odb.c:808
#7  0x00000000004591a9 in git_object_lookup_prefix (object_out=0x7fffdbffeed8, repo=0x7fffec002350, id=0x7fffdbffeee0, len=40, 
    type=GIT_OBJ_ANY) at /home/russell/projects/debian/libgit2/src/object.c:166
#8  0x00000000004592a9 in git_object_lookup (object_out=0x7fffdbffeed8, repo=0x7fffec002350, id=0x7fffdbffeee0, type=GIT_OBJ_ANY)
    at /home/russell/projects/debian/libgit2/src/object.c:201
#9  0x00000000004e474f in cache_quick (arg=0x7fffffffda18) at /home/russell/projects/debian/libgit2/tests/object/cache.c:249
#10 0x00007ffff6a340a4 in start_thread (arg=0x7fffdbfff700) at pthread_create.c:309
#11 0x00007ffff676907d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

output of running cmake on this machine

```
$ cmake ..
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'libcurl'
--   found libcurl, version 7.43.0
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2d") 
-- Found HTTP_Parser: /usr/include  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- checking for module 'libssh2'
--   found libssh2, version 1.5.0
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED - Success
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Failed
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/russell/projects/debian/libgit2/build
```

Please let me know if someone wants a copy of the executable/core I have.

**Comment by carlosmn** [comment]
Some of those tests are more aspirational than anything else. This test uses a repository from multiple threads concurrently, which is not officially supported.

**Comment by russell** [comment]
OK cool, I'm going to disable any of these unstable tests in the Debian packaging scripts.  Thanks for the quick reply.
