### ISSUE TITLE
Segfault in submodule iteration on a bare repository

### ISSUE THREAD

**Issue by jessevdk** [libgit2/libgit2#3901]
In a bare repository there is no working directory, and somewhere along the submodule iteration it expects to find a valid git_config* which is only set if there is a working directory (https://github.com/libgit2/libgit2/blob/c1b370e9313a13df350974e2237997cc651a5d67/src/submodule.c#L459). It then proceeds to try and access fields of a NULL pointer (https://github.com/libgit2/libgit2/blob/c1b370e9313a13df350974e2237997cc651a5d67/src/submodule.c#L161).

**Comment by catskul** [comment]
This happens for me even in a non-bare repository even for: gitg 3.17.1

**Comment by tiennou** [comment]
The ability to load submodules from bare repositories was disabled by 477b3e047426d7ccddb6028416ff0fcc2541a0fd. @pks-t is it something we want to support again ?

@catskul It would be helpful to have a little more context so that the bug can be reproduced. Is it perhaps happening on a publicly accessible repository ?

(@jessevdk Completely unrelated, but the GNOME/gitg GitHub homepage prominently display in its summary a link to "some Trac instance" that provided me with popups and free Adobe Flash Player downloads).

**Comment by pks-t** [comment]
I don't see why we shouldn't support this use case. The only prerequisite is somebody who implements it ;) I don't know if support for loading submodules in a bare repo ever worked or not, but this time around we should definitely have some tests to catch regressions around that functionality.

**Comment by catskul** [comment]
@tiennou unfortunately the repo it's happening for in my case isn't/can't be made public.

Upon further inspection it happens to me in any git repository.

It's happened to me before intermittently, and just as mysteriously occasionally stops happening.

I think I can't provide any more help unless install from source. I might try that soon, but can't at the moment.

Full stack trace if it helps:
`
#0  0x00007ffff0291e7f in git_config_iterator_glob_new () from /usr/lib/x86_64-linux-gnu/libgit2.so.24
#1  0x00007ffff02f19c3 in ?? () from /usr/lib/x86_64-linux-gnu/libgit2.so.24
#2  0x00007ffff02f47d1 in git_submodule_foreach () from /usr/lib/x86_64-linux-gnu/libgit2.so.24
#3  0x00007ffff77254b3 in ggit_repository_submodule_foreach (repository=0x555555aef050, callback=0x7ffff7b97eb0, user_data=0x55555593b2e0, error=0x7fffffffaf58) at ggit-repository.c:2182
#4  0x00007ffff7b98f2d in gitg_repository_list_box_add_repository () from /usr/lib/gitg/libgitg-1.0.so.0
#5  0x00007ffff7b9a4e8 in ?? () from /usr/lib/gitg/libgitg-1.0.so.0
#6  0x00007ffff51eead8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff51efc01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff632b75a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff632de73 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff4f155a3 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff4f16763 in g_markup_parse_context_parse () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff632e8d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff6329b78 in gtk_builder_extend_with_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff6573e07 in gtk_widget_init_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff520c359 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff51eddf8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x000055555558f192 in ?? ()
#18 0x00007ffff51ee149 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff51efc01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff632b75a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff632cb65 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff632e4f1 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff4f156d7 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff4f1652e in g_markup_parse_context_parse () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff632e8d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff6329b78 in gtk_builder_extend_with_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff6573e07 in gtk_widget_init_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff520c359 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff51eddf8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x000055555559c46a in ?? ()
#31 0x00007ffff51ee149 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff51efc01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff51f0534 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x000055555559b775 in gitg_window_create_new ()
#35 0x0000555555585b11 in ?? ()
#36 0x0000555555586019 in ?? ()
#37 0x00007fffef67ce40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#38 0x00007fffef67c8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#39 0x00007ffff51e9cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff51e91d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007ffff52039a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007ffff520408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x000055555558653c in ?? ()
#44 0x00007fffef67ce40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#45 0x00007fffef67c8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#46 0x00007ffff51e9cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff51e91d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#48 0x00007ffff52034b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007ffff520408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007ffff54d7ac3 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#51 0x00007ffff54d9b1d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#52 0x0000555555585a71 in ?? ()
#53 0x00007ffff54d9ce2 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#54 0x000055555559d043 in gitg_main_main ()
#55 0x00007ffff45f8830 in __libc_start_main (main=0x55555556fa40 <main>, argc=1, argv=0x7fffffffcf18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffcf08)
---Type <return> to continue, or q <return> to quit---
    at ../csu/libc-start.c:291
#56 0x000055555556fa89 in _start ()
`

**Comment by tiennou** [comment]
@catskul The stack trace helps, thanks ! The soname tells me you're running v24, so this predates the disabling of bare repositories for being unsupported.

**Comment by jessevdk** [comment]
> (@jessevdk Completely unrelated, but the GNOME/gitg GitHub homepage prominently display in its summary a link to "some Trac instance" that provided me with popups and free Adobe Flash Player downloads).

It's an old link to a site I hosted over which I now no longer own the domain, and it seems the domain was aquired to host malware/ads. I've contacted a GNOME sysadmin to remove the link, thanks for notifying me!!

**Comment by pks-t** [comment]
So in fact it seems like the issue doesn't exist on recent branches anymore, as we're just bailing out in case the repo is bare. We can support submodules for bare repositories, but we'd first have to implement parsing in-memory config files, which if I recall correctly isn't possible right now.

**Comment by ccutrer** [comment]
Here's a vote for submodule support on bare repos. possibly by adding an additional param to explicitly say which branch/tree to look for the .gitmodules file in.

**Comment by pks-t** [comment]
> So in fact it seems like the issue doesn't exist on recent branches anymore, as we're just bailing out in case the repo is bare. We can support submodules for bare repositories, but we'd first have to implement parsing in-memory config files, which if I recall correctly isn't possible right now.

In-memory parsing of configuration files has landed by now, so we shouldn't face any major issues implementing readonly in-memory handling of submodules now.
