### ISSUE TITLE
packbuilder performance/connection timeout

### ISSUE THREAD

**Issue by cschlack** [libgit2/libgit2#5133]
I'm not able to push some big repositories to GitHub using libgit2 -> it's failing with a network error. Is there a way to accelerate the packbuilder and/or to prevent timeouts on the network?

### Reproduction steps

code see https://gist.github.com/cschlack/bbc5ff9afa436ab9db3a3f5add5bdaae
test-repository (one branch, one commit, 24 files, 384MB):
https://github.com/cschlack/beautiful-noise

### Expected behavior

```
> git remote add origin git@github.com:cschlack/newrepo.git
> git push --set-upstream origin master
Enumerating objects: 26, done.
Counting objects: 100% (26/26), done.
Delta compression using up to 4 threads
Compressing objects: 100% (26/26), done.
Writing objects:  0% (0/26), [...]
```
Transmission starts on my machine after 3,5minutes.

### Actual behavior

Output:
```
> remote_push beautiful_noise.git git@github.com/cschlack/newrepo
packbuilder stage 0:  1/0  - 3s
packbuilder stage 1:  0/26 - 3s
[...]
packbuilder stage 1: 24/26 - 412s
packbuilder stage 1: 25/26 - 434s
packbuilder stage 1: 26/26 - 434s
writing objects: 0% (0/26), 12 bytes - 434s
[...]
```

It takes > 7 minutes before transmitting starts.

With an even bigger repository:

```
remote_push even_bigger_repo.git git@github.com/cschlack/newrepo
[...]
packbuilder stage 1: 131/132 - 1079s
packbuilder stage 1: 132/132 - 1107s
SSH could not write data: Failure while draining incoming flow (23)
```

The connection times out!
After > 15 minutes libgit2 exits with a network error.

### Version of libgit2 (release number or SHA1)

libgit2 v0.28.2

### Operating system(s) tested

linux, MacOS

**Comment by stmllr** [comment]
confirmed with Rugged:
Using a clone from https://github.com/cschlack/beautiful-noise, when pushing it to an empty GitHub repository it ends up with SSL error.

``` ruby
require 'rugged'

path = 'beautiful-noise.git'
url = 'https://github.com/stmllr/big-repo.git'
credentials = Rugged::Credentials::UserPassword.new(username: 'USER_TOKEN', password: '')
git = Rugged::Repository.bare(path)
remote = git.remotes.create_anonymous(url)
remote.push(git.refs.map(&:name), credentials: credentials)

Traceback (most recent call last):
        1: from app.rb:8:in `<main>'
app.rb:8:in `push': SSL error: syscall failure: Broken pipe (Rugged::OSError)
```

**Comment by pks-t** [comment]
Jeez, what the heck is that repo. It's not like it is huge by any means, but unpacking these objects really takes ages even with git.git.

I think the problem here is that libgit2 doesn't implement keepalive. By default, git.git will send keepalive packages every 5 seconds when using the smart protocol. This is tunable via the receive.keepAlive and uploadpack.keepAlive option, but libgit2 doesn't do any of that.

So the solution is to implement keepalive support for the smart protocol. I've hacked together PR #5201 that implements it for the receiving side as an RFC. Note that this is for the receiving side currently, not yet for the writing side, so your use case wouldn't yet be helped by it. If #5201 is well received, though, I would take a stab at "uploadpack.keepAlive", as well.
