### ISSUE TITLE
Intermittent "unknown certificate check failure" during Clone on machine with only TLS1.2 enabled, and all other protocols disabled

### ISSUE THREAD

**Issue by jakissel** [libgit2/libgit2#5557]
We have a VM on Windows Server 2019 Datacenter on version 17763.1282 behind a fairly strict firewall. We do have an exception on the firewall to allow connection to github. Due to requirements to use TLS 1.2 only we have the set of registry keys at HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols to have TLS1.2 enabled by default and all other protocols disabled.

### Reproduction steps
I have not found a consistent repro for this bug, it affects our machines randomly. The issue happens on the initial connect to github during a git clone using libgit2sharp. We have two clones in a row, with some git operations inbetween each clone that will only occur if the initial clone succeeds. What we are seeing is that sometime all the operations succeed without a hitch, sometimes the first clone will fail, and the second clone will succeed as well as the operations after the second clone, and we have seen other times where both clones fail.

### Expected behavior
I would like to find the root cause of this behavior and to see if it is determinate, because then we can either address the root cause or implement a very specific retry, because right now our only option is to add in a blind retry and according to the behavior we have observed, it could even fail on retries as well.

### Actual behavior
The exception stack we see in our code that calls LibGit2Sharp is 
    {
        "parsedStack": [
            {
                "assembly": "LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333",
                "method": "LibGit2Sharp.Core.Ensure.HandleError",
                "level": 0,
                "line": 0
            },
            {
                "assembly": "LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333",
                "method": "LibGit2Sharp.Core.Proxy.git_clone",
                "level": 1,
                "line": 0
            },
            {
                "assembly": "LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333",
                "method": "LibGit2Sharp.Repository.Clone",
                "level": 2,
                "line": 0
            }
        ],
        "outerId": "0",
        "message": "unknown certificate check failure",
        "type": "LibGit2Sharp.LibGit2SharpException",
        "id": "4034243"
    }

This is accompanied by an SCHANNEL error logged on the machine at the same time: "A fatal error occurred while creating a TLS client credential. The internal error state is 10013." Implying that there was a failure to decide on a specific TLS algorithm I believe.
### Version of libgit2 (release number or SHA1)
0.26.0.0
### Operating system(s) tested
Windows Server 2019 Datacenter on version 17763.1282

I have read a few other threads in this library referring to the certificate error and saw that in the PR that added some fix for it (https://github.com/libgit2/libgit2/pull/4550) it mentions that if it fails to establish a TLS1.2 connection it will try a lower TLS version, which on our machines would fail as we have disabled them completely through the SCHANNEL keys, and I believe that could even be what is happening here, though I am not sure. Is this the case still, and is there a way to cause LibGit2Sharp to only every try to establish TLS1.2 connections and even retry with TLS1.2 instead of downgrading the TLS version? Otherwise are there further diagnostic steps I can take to find out what's happening?

Thanks!!

**Comment by ethomson** [comment]
Hmm, I've never seen this.  libgit2 doesn't really do anything special here, so I'm curious if you see this sort of behavior with other applications, or just libgit2?  What about `git clone` itself on the command line?

> Is this the case still, and is there a way to cause LibGit2Sharp to only every try to establish TLS1.2 connections and even retry with TLS1.2 instead of downgrading the TLS version?

We don't do any sort of fallback.  We ask the operating system for TLS 1.2 and ignore failures if that request failed.  We don't try to do any detection of TLS 1.2 or fallback to a TLS 1.1 mode.  What the operating system itself does is out of our control, but I don't think that it does anything along these lines, either.

>  creating a TLS client credential

This is suspicious.  We don't support client certificates, but also GitHub shouldn't be requesting them.  So either this is a not-very-good error message or I don't understand what a "client credential" is in this context.

**Comment by jakissel** [comment]
Hi @ethomson , Thanks so much for the response! The trouble I am having with this bug is that it happens very randomly and not very frequently. I have experienced cases on the nodes where it fails to connect to github through Internet Explorer and shows some similar failure to establish secure connection in the browser so I am following up with the WinHTTP team, as it seems like this could possibly be an issue where WinHTTP is trying to downgrade to a tls version that is disabled on our machine. Thanks for helping me rule out libgit2 as a possibility. I will update this thread if I find a resolution for where this behavior is coming from (our new working hypothesis is that our firewall is being a little to restrictive on some occasions). Maybe it would be useful to know for if other users experience the same thing on machines that are seemingly configured correctly for TLS1.2 connections.

**Comment by gfollic** [comment]
Hi,
Same issue here:
LibGit2Sharp.LibGit2SharpException : unknown certificate check failure
at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)

Completely random.
using windows 2016 server with LibGit2Sharp 0.26.2 through Teamcity build

**Comment by gfollic** [comment]
@jakissel Did you manage to fix the issue ?
Had to switch to windows 10 instead of Windows 2016 server to solve the issue.

**Comment by zitaszocs** [comment]
Hello,
I have the same problem with libgit2 1.2.0.0 in a Windows 7 64 bit virtual box VM. (I know it is not ok to use Win7, but our clients are still using). I've tried with command line and it works fine.
