### ISSUE TITLE
RPATH default for cmake to allow side-loaded shared libraries on macOS

### ISSUE THREAD

**Issue by frindler** [libgit2/libgit2#6821]
When compiling libgit2 for macOS with libssh2 and OpenSSL for SSH/HTTPS support, CMake does not automatically set the correct RPATH to allow the side-loading of the libs.

### Reproduction steps

Compile with SSH/OpenSSL support:

```
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_OSX_ARCHITECTURES=arm64 \
      -DUSE_SSH=libssh2 \
      -DUSE_HTTPS=OpenSSL \
      .
```
(I've omitted some parameters for prefix etc.)

### Expected behavior

Generated dylib should work.

### Actual behavior

When trying to load the dylib (I'm doing this from C#), I get an error referencing missing `LC_RPATH`s (the following is shortened for clarity):

```
Unable to load shared library 'git2-a418d9d' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
...
dlopen(/project-path/bin/Debug/net8.0/runtimes/osx-arm64/native/libgit2-a418d9d.dylib, 0x0001): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: <F5D6D3ED-E6CE-3236-85A1-2FED8DCD352B> /project-path/bin/Debug/net8.0/runtimes/osx-arm64/native/libgit2-a418d9d.dylib
  Reason: no LC_RPATH's found
...
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary() in /project-path/LibGit2Sharp/Core/NativeMethods.cs:line 148
   at LibGit2Sharp.Core.NativeMethods..cctor() in /project-path/LibGit2Sharp/Core/NativeMethods.cs:line 54

```

### Version of libgit2 (release number or SHA1)

1.7.2 (because that's what LibGit2Sharp currently uses), but I couldn't see any relevant changes in more recent CMake files.

### Operating system(s) tested

macOS on arm64

**Comment by frindler** [comment]
### Analysis & fix

The reason is that the RPATHs have not been set, so the dylib loader is not finding the side dylib `libssh2.1.dylib`.

This can be fixed by adding `-DCMAKE_INSTALL_RPATH='@loader_path'` on macOS (and presumably `-DCMAKE_INSTALL_RPATH='$ORIGIN'` on UNIX) to the cmake command above.

This kind of thing seems to be considered a library bug by the DOTNET team at least, see https://github.com/dotnet/runtime/pull/96367#issuecomment-1872602767 , where they propose to add `-rpath` to the clang commands.

An alternative is to add the following to `CMakeLists.txt`:

```
# Ensure proper loading of side-loaded shared libraries
# on all targets.
set(CMAKE_SKIP_BUILD_RPATH FALSE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
if(APPLE)
    set(CMAKE_INSTALL_RPATH "@loader_path")
elseif(UNIX)
    set(CMAKE_INSTALL_RPATH "\$ORIGIN")
endif()
```

(this is taken from https://github.com/rhymu8354/Excalibur/blob/main/CMakeLists.txt)

This is a real gotcha for people trying to compile libgit2 with SSH/HTTPS support (took me hours to figure out) and this wasn't a problem a while ago when there were no side libraries. When I compiled libgit2 at 1.3.0 there was no problem as there were no side dylibs (perhaps https://github.com/libgit2/libgit2/commit/3bd9bb8d77521f3fb0181366463e1c93d48aaa2e caused this?).

The cmake structure of libgit2 seems complex, so I'm not raising a PR for this. Someome from the libgit2 team will know better what to do here.
